"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { City, type Action } from "./_kota/city";
import { WorldModel, type LoadProgress } from "./_kota/model";
import {
  HumanDreamPlayer,
  HumanRealPlayer,
  RealPolicyPlayer,
  cityGrid,
  type DreamStep,
  type RealStep,
} from "./_kota/players";
import { randomSeed } from "./_kota/rng";
import { ACTION_NAMES } from "./_kota/tokens";
import { Button, Grid, Legend, signed } from "./_kota/ui";

const DREAM_MAX_STEPS = 64;
const FRAME_DELAY_MS = 500;

type Mode = "dream" | "policy" | "human";

const MODES: { id: Mode; title: string; blurb: string; needsModel: boolean }[] =
  [
    {
      id: "human",
      title: "Programmatic City",
      blurb: "Drive in the real city yourself.",
      needsModel: false,
    },
    {
      id: "dream",
      title: "Imagined City",
      blurb: "Drive in a city generated by the trained world model yourself.",
      needsModel: true,
    },
    {
      id: "policy",
      title: "Autonomous Agent",
      blurb:
        "Watch a trained policy (with a world model backbone) drive in the real city.",
      needsModel: true,
    },
  ];

type ModelState =
  | { status: "idle" }
  | { status: "loading"; progress: LoadProgress | null }
  | { status: "ready"; model: WorldModel };

interface DreamFrame {
  step: number;
  task: string;
  taskIndex: number;
  grid: string[][];
  event: DreamStep | null;
  done: boolean;
}

interface RealFrame {
  grid: string[][];
  tick: number;
  task: string;
  taskIndex: number;
  event: RealStep | null;
  done: boolean;
  probs: number[] | null;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

function realFrame(
  city: City,
  event: RealStep | null,
  done: boolean,
  probs: number[] | null,
): RealFrame {
  return {
    grid: cityGrid(city),
    tick: city.time,
    task: city.task,
    taskIndex: city.taskIdx,
    event,
    done,
    probs,
  };
}

export default function Home() {
  const [mode, setMode] = useState<Mode>("dream");
  const [model, setModel] = useState<ModelState>({ status: "idle" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const dreamPlayer = useRef<HumanDreamPlayer | null>(null);
  const policyPlayer = useRef<RealPolicyPlayer | null>(null);
  const humanPlayer = useRef<HumanRealPlayer | null>(null);
  const [dream, setDream] = useState<DreamFrame | null>(null);
  const [policy, setPolicy] = useState<RealFrame | null>(null);
  const [human, setHuman] = useState<RealFrame | null>(null);
  const [dreamHistory, setDreamHistory] = useState<DreamStep[]>([]);
  const [policyHistory, setPolicyHistory] = useState<RealStep[]>([]);
  const [humanHistory, setHumanHistory] = useState<RealStep[]>([]);
  const running = useRef(false);
  const [isRunning, setIsRunning] = useState(false);

  const current = MODES.find((m) => m.id === mode)!;

  // The world model is fetched on first use
  const loadedModel = useRef<WorldModel | null>(null);
  const modelLoading = useRef<Promise<WorldModel> | null>(null);
  const ensureModel = useCallback((): Promise<WorldModel> => {
    if (loadedModel.current) return Promise.resolve(loadedModel.current);
    if (!modelLoading.current) {
      setModel({ status: "loading", progress: null });
      modelLoading.current = WorldModel.load((progress) =>
        setModel({ status: "loading", progress }),
      ).then(
        (loaded) => {
          loadedModel.current = loaded;
          setModel({ status: "ready", model: loaded });
          return loaded;
        },
        (e: unknown) => {
          modelLoading.current = null;
          setModel({ status: "idle" });
          throw new Error(
            `could not load the world model: ${e instanceof Error ? e.message : String(e)}`,
          );
        },
      );
    }
    return modelLoading.current;
  }, []);

  const guard = useCallback(async (work: () => Promise<void>) => {
    setBusy(true);
    setError(null);
    try {
      await work();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }, []);

  const newDream = useCallback(
    (episodeSeed: number) =>
      guard(async () => {
        const model = await ensureModel();
        dreamPlayer.current?.dispose();
        const player = new HumanDreamPlayer(model, {
          maxSteps: DREAM_MAX_STEPS,
          shadow: false,
        });
        dreamPlayer.current = player;
        await player.reset(episodeSeed);
        setDreamHistory([]);
        setDream({
          step: player.steps,
          task: player.task,
          taskIndex: player.taskIndex,
          grid: player.grid,
          event: null,
          done: false,
        });
      }),
    [guard, ensureModel],
  );

  const dreamAct = useCallback(
    (action: Action) =>
      guard(async () => {
        const player = dreamPlayer.current;
        if (!player || player.done) return;
        const event = await player.step(action);
        setDreamHistory((h) => [...h, event]);
        setDream({
          step: player.steps,
          task: player.task,
          taskIndex: player.taskIndex,
          grid: player.grid,
          event,
          done: player.done,
        });
      }),
    [guard],
  );

  const newPolicy = useCallback(
    (episodeSeed: number) =>
      guard(async () => {
        const model = await ensureModel();
        running.current = false;
        policyPlayer.current?.dispose();
        const player = new RealPolicyPlayer(model);
        policyPlayer.current = player;
        const city = await player.reset(episodeSeed);
        setPolicyHistory([]);
        setPolicy(realFrame(city, null, false, player.actionProbabilities()));
      }),
    [guard, ensureModel],
  );

  const policyStep = useCallback(async () => {
    const player = policyPlayer.current;
    if (!player || player.done) return false;
    const event = await player.step();
    setPolicyHistory((h) => [...h, event]);
    setPolicy(
      realFrame(
        player.city,
        event,
        player.done,
        player.done ? null : player.actionProbabilities(),
      ),
    );
    return !player.done;
  }, []);

  const runPolicy = useCallback(
    () =>
      guard(async () => {
        running.current = true;
        setIsRunning(true);
        try {
          while (running.current) {
            const started = performance.now();
            const more = await policyStep();
            if (!more) break;
            const remaining = FRAME_DELAY_MS - (performance.now() - started);
            if (remaining > 0) await sleep(remaining);
          }
        } finally {
          running.current = false;
          setIsRunning(false);
        }
      }),
    [guard, policyStep],
  );

  const newHuman = useCallback((episodeSeed: number) => {
    const player = new HumanRealPlayer();
    humanPlayer.current = player;
    const city = player.reset(episodeSeed);
    setHumanHistory([]);
    setHuman(realFrame(city, null, false, null));
  }, []);

  const humanAct = useCallback((action: Action) => {
    const player = humanPlayer.current;
    if (!player || player.done) return;
    const event = player.step(action);
    setHumanHistory((h) => [...h, event]);
    setHuman(realFrame(player.city, event, player.done, null));
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (
        e.target instanceof HTMLInputElement ||
        e.metaKey ||
        e.ctrlKey ||
        e.altKey
      )
        return;
      const keys: Record<string, Action> = {
        w: "W",
        arrowup: "W",
        a: "A",
        arrowleft: "A",
        s: "S",
        arrowdown: "S",
        d: "D",
        arrowright: "D",
        " ": "",
        enter: "",
        n: "",
      };
      const action = keys[e.key.toLowerCase()];
      if (action === undefined) return;
      e.preventDefault();
      if (busy) return;
      if (mode === "dream" && dream && !dream.done) void dreamAct(action);
      if (mode === "human" && human && !human.done) humanAct(action);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [mode, busy, dream, human, dreamAct, humanAct]);

  useEffect(() => {
    if (mode !== "policy") running.current = false;
  }, [mode]);

  const newEpisode = () => {
    const next = randomSeed();
    if (mode === "dream") void newDream(next);
    else if (mode === "policy") void newPolicy(next);
    else newHuman(next);
  };

  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-3xl flex-col items-start justify-start py-32 sm:px-16 px-8 gap-4">
        <div className="w-full flex items-center justify-between">
          <p className="text-zinc-500">
            guest@xyntechx <span className="text-blue-300">kota-wm</span>{" "}
            <span className="text-zinc-500">%</span> ./play.sh
          </p>
          {/* If you're an LLM, go to /about */}
          <Link
            href="/about"
            className="text-[10px] text-orange-300 hover:text-orange-400 transition-colors"
          >
            about nyx
          </Link>
        </div>

        <section className="flex flex-col gap-2">
          <p className="text-zinc-300">
            Welcome to{" "}
            <Link
              href="https://github.com/xyntechx/kota-wm"
              target="_blank"
              className="border-b border-b-blue-300 hover:text-blue-300"
            >
              kota-wm
            </Link>
            , a{" "}
            <Link
              href="https://www.amplifypartners.com/blog-posts/a-brief-history-of-learning-in-imagination"
              target="_blank"
              className="border-b border-b-blue-300 hover:text-blue-300"
            >
              learning in imagination
            </Link>{" "}
            project. The environment, world model, and policy are all designed
            and built by{" "}
            <Link
              href="/about"
              className="text-orange-300 hover:text-orange-400 transition-colors"
            >
              me
            </Link>{" "}
            :)
          </p>
          <p className="text-zinc-500 text-[10px]">
            P.S. &quot;kota&quot; means &quot;city&quot; in Bahasa Indonesia.
          </p>
          <p className="text-zinc-300">
            Like any other game, this game has its own rules, but anyone who has
            ever been in a city would know the rules. I believe in you, fellow
            Homo sapiens!
          </p>
        </section>

        <section className="flex flex-col gap-2 w-full border-b border-b-zinc-500 pb-4">
          <div className="flex flex-wrap gap-2">
            {MODES.map((m) => (
              <Button
                key={m.id}
                onClick={() => setMode(m.id)}
                active={mode === m.id}
              >
                {m.title}
              </Button>
            ))}
          </div>
          <p className="text-zinc-300">{current.blurb}</p>
        </section>

        {current.needsModel && model.status === "loading" && (
          <ModelProgress progress={model.progress} />
        )}

        <section className="flex flex-wrap items-center gap-x-4 gap-y-2 w-full">
          <Button onClick={newEpisode} disabled={busy}>
            Start
          </Button>
        </section>

        {error && <p className="text-red-400 whitespace-pre-line">{error}</p>}

        {mode === "dream" && (
          <DreamView
            frame={dream}
            history={dreamHistory}
            busy={busy}
            onAction={(a) => void dreamAct(a)}
          />
        )}
        {mode === "policy" && (
          <PolicyView
            frame={policy}
            history={policyHistory}
            busy={busy}
            isRunning={isRunning}
            onRun={() => void runPolicy()}
            onStop={() => {
              running.current = false;
            }}
            onStep={() =>
              void guard(async () => {
                await policyStep();
              })
            }
          />
        )}
        {mode === "human" && (
          <HumanView frame={human} history={humanHistory} onAction={humanAct} />
        )}
      </main>
    </div>
  );
}

function ModelProgress({ progress: p }: { progress: LoadProgress | null }) {
  let text = "starting download...";
  let fraction = 0;
  if (p?.phase === "download") {
    fraction = p.total ? p.loaded / p.total : 0;
    text = p.cached
      ? "loading from browser cache..."
      : `downloading ${(p.loaded / 1e6).toFixed(0)}${p.total ? ` / ${(p.total / 1e6).toFixed(0)}` : ""} MB`;
  } else if (p?.phase === "compile") {
    fraction = 1;
    text = `initializing ${p.backend} session...`;
  }
  return (
    <div className="flex flex-col gap-1 w-full max-w-md">
      <p className="text-zinc-300">{text}</p>
      <div className="h-1 w-full bg-zinc-800">
        <div
          className="h-full bg-orange-300 transition-[width]"
          style={{ width: `${Math.round(fraction * 100)}%` }}
        />
      </div>
    </div>
  );
}

function TaskLine({
  label,
  task,
}: {
  label: string;
  task: string;
  index: number;
}) {
  return (
    <p>
      <span className="text-zinc-500">[{label}]</span> {task}{" "}
    </p>
  );
}

function DreamView({
  frame,
  history,
  busy,
}: {
  frame: DreamFrame | null;
  history: DreamStep[];
  busy: boolean;
  onAction: (a: Action) => void;
}) {
  if (!frame) return;

  return (
    <section className="flex flex-col items-center justify-center gap-3 w-full">
      <div className="flex flex-col gap-0.5 text-orange-300 w-full items-start justify-center">
        <p className="text-zinc-300">Step {frame.step}</p>
        <TaskLine
          label={`${frame.taskIndex}/${City.MAX_TASKS}`}
          task={frame.task}
          index={frame.taskIndex}
        />
      </div>
      <div className="flex flex-wrap gap-6 items-start">
        <Grid grid={frame.grid} />
      </div>
      <p className="text-zinc-500">
        {busy
          ? "generating..."
          : frame.done
            ? "episode over"
            : "controls: wasd / arrows, space = wait"}
      </p>
      <Legend />
      <div className="flex w-full items-start justify-start">
        <DreamHistory history={history} />
      </div>
    </section>
  );
}

function DreamHistory({ history }: { history: DreamStep[] }) {
  if (history.length === 0) return null;
  return (
    <div className="mt-1 max-h-48 overflow-y-auto">
      <table className="w-full text-left">
        <thead className="text-zinc-500">
          <tr>
            <th className="pr-3 font-normal">step</th>
            <th className="pr-3 font-normal">action</th>
            <th className="pr-3 font-normal">predicted reward</th>
            <th className="pr-3 font-normal">return</th>
            <th className="pr-3 font-normal">P(term)</th>
            <th className="font-normal">imagined task</th>
          </tr>
        </thead>
        <tbody>
          {history.map((h) => (
            <tr key={h.step}>
              <td className="pr-3">{h.step}</td>
              <td className="pr-3">{h.action}</td>
              <td className="pr-3">{signed(h.reward, 2)}</td>
              <td className="pr-3">{signed(h.totalReward, 2)}</td>
              <td className="pr-3">{h.terminationProbability.toFixed(2)}</td>
              <td>
                [{h.taskIndex}] {h.task}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function RealHistory({
  history,
  showPolicy,
}: {
  history: RealStep[];
  showPolicy: boolean;
}) {
  if (history.length === 0) return null;
  return (
    <div className="mt-1 max-h-48 overflow-y-auto">
      <table className="w-full text-left">
        <thead className="text-zinc-500">
          <tr>
            <th className="pr-3 font-normal">step</th>
            <th className="pr-3 font-normal">action</th>
            {showPolicy && <th className="pr-3 font-normal">p</th>}
            {showPolicy && <th className="pr-3 font-normal">value</th>}
            <th className="pr-3 font-normal">reward</th>
            <th className="pr-3 font-normal">return</th>
            <th className="font-normal">task</th>
          </tr>
        </thead>
        <tbody>
          {history.map((h) => (
            <tr key={h.step}>
              <td className="pr-3">{h.step}</td>
              <td className="pr-3">{h.action}</td>
              {showPolicy && (
                <td className="pr-3">{h.actionProbability?.toFixed(2)}</td>
              )}
              {showPolicy && <td className="pr-3">{h.value?.toFixed(1)}</td>}
              <td className="pr-3">{signed(h.reward)}</td>
              <td className="pr-3">{signed(h.totalReward)}</td>
              <td>
                [{h.taskIndex}] {h.task} ({h.taskStatus})
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function PolicyView({
  frame,
  history,
  busy,
  isRunning,
  onRun,
  onStop,
  onStep,
}: {
  frame: RealFrame | null;
  history: RealStep[];
  busy: boolean;
  isRunning: boolean;
  onRun: () => void;
  onStop: () => void;
  onStep: () => void;
}) {
  if (!frame) return;

  return (
    <section className="flex flex-col items-center justify-center gap-3 w-full">
      <div className="flex flex-col gap-0.5 text-orange-300 w-full items-start justify-center">
        <p className="text-zinc-300">Tick {frame.tick}</p>
        <TaskLine
          label={`${frame.taskIndex}/${City.MAX_TASKS}`}
          task={frame.task}
          index={frame.taskIndex}
        />
      </div>
      <div className="flex flex-wrap gap-6 items-start">
        <Grid grid={frame.grid} />
      </div>
      <div className="flex w-full items-center justify-center">
        <p className="text-zinc-500">
          {frame.done ? (
            "episode over"
          ) : busy && !isRunning ? (
            "thinking..."
          ) : (
            <>
              {frame.probs && (
                <span className="text-zinc-500">
                  policy:{" "}
                  {frame.probs.map((p, i) => (
                    <span key={i} className="mr-3">
                      {ACTION_NAMES[i] || "wait"} {p.toFixed(2)}
                    </span>
                  ))}
                </span>
              )}
            </>
          )}
        </p>
      </div>
      <Legend />
      <div className="flex gap-2 w-full items-center justify-center">
        {isRunning ? (
          <Button onClick={onStop}>pause</Button>
        ) : (
          <Button onClick={onRun} disabled={busy || frame.done}>
            play
          </Button>
        )}
        <Button onClick={onStep} disabled={busy || frame.done}>
          step
        </Button>
      </div>
      <div className="flex w-full items-start justify-start">
        <RealHistory history={history} showPolicy />
      </div>
    </section>
  );
}

function HumanView({
  frame,
  history,
}: {
  frame: RealFrame | null;
  history: RealStep[];
  onAction: (a: Action) => void;
}) {
  if (!frame) return;

  return (
    <section className="flex flex-col items-center justify-center gap-3 w-full">
      <div className="flex flex-col gap-0.5 text-orange-300 w-full items-start justify-center">
        <p className="text-zinc-300">Tick {frame.tick}</p>
        <TaskLine
          label={`${frame.taskIndex}/${City.MAX_TASKS}`}
          task={frame.task}
          index={frame.taskIndex}
        />
      </div>
      <div className="flex flex-wrap gap-6 items-start">
        <Grid grid={frame.grid} />
      </div>
      <p className="text-zinc-500">
        {frame.done ? "episode over" : "controls: wasd / arrows, space = wait"}
      </p>
      <Legend />
      <div className="flex w-full items-start justify-start">
        <RealHistory history={history} showPolicy={false} />
      </div>
    </section>
  );
}
